### ISSUE TITLE
Failed to start server.js

### ISSUE THREAD

**Issue by justvanbloom** [szimek/xmpp-chat#10]
Hi. Which version to use?
I have
npm 1.1.32
Nodejs 0.6.19

node  server.js

/xmpp-chat/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:53
    throw new Error('Both `options` and `options.target` are required.');
          ^
Error: Both `options` and `options.target` are required.
    at new <anonymous> (/xmpp-chat/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:53:11)
    at Object.<anonymous> (/xmpp-chat/server.js:9:13)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
    at EventEmitter._tickCallback (node.js

**Comment by szimek** [comment]
On 1 July 2012 19:40, JustVanBlooM
reply@reply.github.com
wrote:

> Hi. Which version to use?
> I have
> npm 1.1.32
> Nodejs 0.6.19
> 
> node  server.js
> 
> /xmpp-chat/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:53
>     throw new Error('Both `options` and `options.target` are required.');
>           ^
> Error: Both `options` and `options.target` are required.
>     at new <anonymous> (/xmpp-chat/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:53:11)
>     at Object.<anonymous> (/xmpp-chat/server.js:9:13)
>     at Module._compile (module.js:446:26)
>     at Object..js (module.js:464:10)
>     at Module.load (module.js:353:31)
>     at Function._load (module.js:311:12)
>     at Array.0 (module.js:484:10)
>     at EventEmitter._tickCallback (node.js
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/szimek/xmpp-chat/issues/10

Hi!

Could you check out branch http-proxy
(https://github.com/szimek/xmpp-chat/tree/http-proxy) and let me know
if it works? If it does, I'll merge it to master.

Cheers.
Szymon

**Comment by justvanbloom** [comment]
yep worked :P

**Comment by abhay-singh** [comment]
I have problem with server.js to run with node it gives Error is that

module.js:340
throw err;

Error: cannot find module 'express'
at Function.Module._resolveFilenamemodule.js:338:15
at Function.Module._loadmodule.js:280:25
at Module. require module.js:362:17

## at Object.<anonymous> 

---

please help me to run successfully on my system....

**Comment by justvanbloom** [comment]
U need to setup modules needed. 'npm install express'
