### ISSUE TITLE
XMPP Support from Facebook.

### ISSUE THREAD

**Issue by amirjamil90** [szimek/xmpp-chat#21]
Has Facebook completed blocked XMPP Webchats or is there a way to use this XMPP Protocol in Facebook ????

**Comment by amirjamil90** [comment]
@szimek Please update on this ?

**Comment by szimek** [comment]
@amirjamil90 I have no idea. I haven't touch this project since 2013.

**Comment by amirjamil90** [comment]
Okk ...

**Comment by amirjamil90** [comment]
Issue Resolved
